#!/usr/bin/env python3
"""Run EDA and write notes/eda_summary.md (Phase 2)."""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT))

from config import TARGET_LABELS  # noqa: E402
from src.data import load_train, load_train_series, load_test  # noqa: E402
from src.labels import add_weak_labels, labeled_mask  # noqa: E402

NOTES = PROJECT / "notes"
NOTES.mkdir(parents=True, exist_ok=True)


def detect_language_hints(reports: pd.Series) -> dict[str, int]:
    """Very rough language cues for EDA (not a full language ID)."""
    text = reports.fillna("").astype(str)
    cues = {
        "has_spanish_tokens": text.str.contains(
            r"\b(?:rodilla|informe|ligamento|menisco)\b", case=False, regex=True
        ).sum(),
        "has_french_tokens": text.str.contains(
            r"\b(?:genou|compte rendu|ligament|ménisque|menisque)\b", case=False, regex=True
        ).sum(),
        "has_german_tokens": text.str.contains(
            r"\b(?:knie|befund|bandruptur|meniskus)\b", case=False, regex=True
        ).sum(),
        "mostly_ascii_englishish": text.str.contains(
            r"\b(?:mri|knee|tear|effusion|meniscus|acl)\b", case=False, regex=True
        ).sum(),
    }
    return {k: int(v) for k, v in cues.items()}


def main() -> None:
    train = load_train()
    series = load_train_series()
    test = load_test()

    mask = labeled_mask(train)
    labeled = train.loc[mask]
    report_lens = train["Report"].fillna("").astype(str).str.len()
    missing_reports = int(train["Report"].isna().sum() + (train["Report"].fillna("").astype(str).str.strip() == "").sum())

    # Prevalence among labeled rows with non-null label
    prevalence_lines = []
    imbalance = []
    for lab in TARGET_LABELS:
        col = labeled[lab]
        non_null = col.notna().sum()
        if non_null == 0:
            prevalence_lines.append(f"| {lab} | 0 | n/a |")
            continue
        pos = int((col == 1).sum())
        rate = pos / non_null
        imbalance.append((lab, rate, non_null, pos))
        prevalence_lines.append(f"| {lab} | {non_null} | {rate:.1%} ({pos}/{non_null}) |")

    imbalance_sorted = sorted(imbalance, key=lambda x: x[1])
    rare = ", ".join(f"{n} ({r:.1%})" for n, r, _, _ in imbalance_sorted[:3]) if imbalance_sorted else "n/a"
    common = ", ".join(f"{n} ({r:.1%})" for n, r, _, _ in imbalance_sorted[-3:][::-1]) if imbalance_sorted else "n/a"

    # Weak vs expert agreement on labeled subset
    weak_df = add_weak_labels(labeled.copy())
    agree_per = {}
    for lab in TARGET_LABELS:
        y = weak_df[lab]
        w = weak_df[f"weak_{lab}"]
        m = y.notna()
        if m.sum() == 0:
            continue
        agree_per[lab] = float((y[m].astype(float) == w[m].astype(float)).mean())
    mean_agree = float(np.mean(list(agree_per.values()))) if agree_per else float("nan")

    series_per = series.groupby("StudyInstanceUID").size()
    plane_counts = series["Anatomical_Plane"].value_counts().to_dict() if "Anatomical_Plane" in series.columns else {}
    fluid = (
        int(series["Fluid_Sensitive"].sum())
        if "Fluid_Sensitive" in series.columns
        else 0
    )

    lang = detect_language_hints(train["Report"])
    test_has_report = "Report" in test.columns

    lines = [
        "# EDA Summary — RSNA Knee Abnormality Detection",
        "",
        f"_Generated by `scripts/run_eda.py`. Data root studies: {len(train):,}._",
        "",
        "## Dataset sizes",
        "",
        f"| Split | Studies | Series |",
        f"|-------|---------|--------|",
        f"| train | {len(train):,} | {len(series):,} |",
        f"| test (local) | {len(test):,} | (see test_series.csv) |",
        f"| Series per study (median / mean) | {series_per.median():.0f} / {series_per.mean():.1f} | |",
        "",
        "## Labels",
        "",
        f"- Expert-labeled studies: **{mask.sum():,} / {len(train):,} ({100 * mask.mean():.1f}%)**",
        f"- Unlabeled (report-only) studies: **{(~mask).sum():,}**",
        "",
        "| Label | Non-null (labeled set) | Positive rate |",
        "|-------|------------------------|---------------|",
        *prevalence_lines,
        "",
        f"- Rarest (among labeled): {rare}",
        f"- Most common (among labeled): {common}",
        "",
        "## Reports",
        "",
        f"- Missing/empty reports on train: **{missing_reports}**",
        f"- Report length (chars): median **{report_lens.median():.0f}**, mean **{report_lens.mean():.0f}**, max **{report_lens.max():.0f}**",
        f"- Test CSV has `Report` column: **{test_has_report}** "
        + ("(still treat as unreliable for hidden test)" if test_has_report else "(mirrors competition — text model needs image fallback)"),
        "",
        "### Language cues (heuristic token counts)",
        "",
        "| Cue | Count |",
        "|-----|-------|",
        *[f"| {k} | {v} |" for k, v in lang.items()],
        "",
        "## Series metadata",
        "",
        f"- Plane counts: {plane_counts}",
        f"- Fluid-sensitive series count: {fluid}",
        "",
        "## Weak keyword labels vs expert",
        "",
        f"- Mean agreement on labeled set: **{mean_agree:.1%}**",
        "",
        "| Label | Agreement |",
        "|-------|-----------|",
        *[f"| {k} | {v:.1%} |" for k, v in agree_per.items()],
        "",
        "## Risks for modeling",
        "",
        "1. **Partial labels** — do not fill NaN as 0 without documenting bias.",
        "2. **Class imbalance** — rare findings (e.g. Fracture, Baker's) dominate AUC instability.",
        "3. **Multilingual reports** — English-only TF-IDF / keywords underperform on non-English text.",
        "4. **Test without reports** — image path required for competitive LB.",
        "5. **Site / protocol shift** — intensity, plane naming, and transfer syntax vary.",
        "",
        "## Exit criteria (Phase 2)",
        "",
        "- [x] Sizes recorded",
        "- [x] % labeled recorded",
        "- [x] Imbalance ranking recorded",
        "- [x] Reports may be missing at test noted",
        "",
    ]
    out = NOTES / "eda_summary.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
